users_create_per_user_group: false
users_create_homedirs: true

users:
- username: peter
  groups: ['adm','sudo']
  uid: 500
  shell: /bin/zsh
  # pip install passlib
  # python3 -c "from passlib.hash import sha512_crypt; print(sha512_crypt.encrypt('password'))"
  password: '$6$rounds=100000$r2DvUWNVReVMgErI$thwYEluyYIicV8GG6BI8rfPnJgUBO7SWIp47Zz1gJ/ZtXYq1CrROUVdmstX8Qg2IouW.dnpPmeDvgRas5GlCY.'
